### ISSUE TITLE
Deleting more than 20 packages at a time.

### ISSUE THREAD

**Issue by cricketsamya** [SmartsquareGmbH/delete-old-packages#18]
may be a param can be added that will allow to delete more than 20 packages.
```Error: names cannot contain more than 20 items
    at new Strategy (/home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:60269)
    at new RepoStrategy (/home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:58597)
    at getStrategyFromInput (/home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:64024)
    at /home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:64106
    at /home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:64165
    at Object.<anonymous> (/home/runner/work/_actions/smartsquaregmbh/delete-old-packages/v0.3.1/dist/index.js:13:64204)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)```

**Comment by rubengees** [comment]
The Github api has rate limits and our limit of 20 is set to avoid running into them. I would suggest to run the action multiple times (e.g. with a [cron schedule](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events)) until all packages you want to delete are done.
